GET http://localhost:3000/users

###
GET http://localhost:3000/users/612a3b257eb902c64ac067dd


###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Kenzo", 
    "dob": "July 1, 1991",
    "address": "BLK 69 Hello World Singapore",
    "description": "Testing POST request - Saravillo"
}

###
DELETE http://localhost:3000/users/612b32f6deb4951b3fa9b157


###
PATCH http://localhost:3000/users/612a442f32a2bd34004e382c
Content-Type: application/json

{
    "name": "Hello", 
    "dob": "July 2, 1990",
    "address": "BLK 1234",
    "description": "Testing, to update information through Patch method."
}

